language: python

python:
- '2.7'
- '3.6'
- '3.7-dev'

sudo: false

env:
  PYTHONPATH: plugin.video.vrt.nu

install:
- pip install -r requirements.txt

script:
- tox
- pylint plugin.video.vrt.nu/*.py
- pylint plugin.video.vrt.nu/lib/*/*.py
- python test/vrtplayertests.py
